import type { Locale } from "@/i18n/routing";

/**
 * The words of the HDC emails, per language.
 *
 * Customer emails go out in the customer's language (el/en/it); the shop's
 * internal emails and the admin password reset are Greek only, so their words
 * live in `INTERNAL` and exist once.
 *
 * `{name}` is a placeholder filled by `t()`; a missing value throws rather than
 * printing an empty gap in front of a customer. Keys ending in `_html` may
 * carry markup of our own; their placeholders are still escaped.
 *
 * Words only for individuals (the HDC sells to private buyers), and the HDC is
 * never called a dealer or an authorised agent of anyone.
 */

const el = {
  "nav.offers": "Προσφορές",

  "footer.store": "Το κατάστημα στον Πειραιά",
  "footer.sunday": "Κυριακή κλειστά",
  "footer.directions": "Οδηγίες στον χάρτη",
  "footer.contact": "Επικοινωνία",
  "footer.preferences": "Προτιμήσεις email",
  "footer.unsubscribe": "Διαγραφή από τη λίστα",
  "footer.operator_html":
    'Το Milwaukee Heavy Duty Centre Πειραιά λειτουργεί από την <b style="color:#ffffff;">{company}</b> · ΑΦΜ {vat} · ΓΕΜΗ {gemi}.',
  "footer.trademarks":
    "Τα Milwaukee®, M12™, M18™, MX FUEL™, PACKOUT™, ONE-KEY™ και REDLITHIUM™ είναι εμπορικά σήματα της Milwaukee Tool.",
  "footer.terms": "Όροι χρήσης",
  "footer.privacy": "Απόρρητο",
  "footer.why_newsletter":
    "Λαμβάνετε αυτό το email επειδή εγγραφήκατε στο newsletter του Milwaukee Heavy Duty Centre.",
  "footer.why_order":
    "Λαμβάνετε αυτό το email επειδή κάνατε παραγγελία στο {site}. Είναι ενημέρωση για την παραγγελία σας και δεν είναι διαφημιστικό.",
  "footer.why_account":
    "Λαμβάνετε αυτό το email για τον λογαριασμό σας στο {site}. Δεν είναι διαφημιστικό.",
  "footer.why_subscribe":
    "Λαμβάνετε αυτό το email επειδή ζητήθηκε εγγραφή στο newsletter του {site} με αυτή τη διεύθυνση.",

  hours: "Δευ–Παρ {wo}–{wc} · Σάβ {so}–{sc}",

  "help.call": "Καλέστε μας στο",
  "help.or_reply": "ή απαντήστε σε αυτό το email.",
  "help.order": "Ερωτήσεις για την παραγγελία;",
  "help.account": "Χρειάζεστε βοήθεια;",

  "card.view": "Δείτε το",
  "card.bare": "Χωρίς μπαταρία",
  "card.new": "Νέο",
  "avail.se_apothema": "Σε απόθεμα",
  "avail.teleftaio": "Τελευταίο τεμάχιο",
  "avail.diathesimo_3_5": "Διαθέσιμο · 3–5 εργάσιμες",
  "avail.paradosi_1_3": "Παράδοση 1–3 εργάσιμες",

  "line.code": "Κωδ.",
  "line.qty": "Ποσότητα",

  "order.number": "Αριθμός παραγγελίας",
  "order.date": "Ημερομηνία",
  "order.status": "Κατάσταση",
  "order.items": "Τα είδη σας ({count})",
  "order.prices_gross": "Τιμές με ΦΠΑ",
  "order.total": "Σύνολο",
  "order.subtotal": "Υποσύνολο",
  "order.discount": "Έκπτωση",
  "order.shipping": "Μεταφορικά · {method}",
  "order.payment_fee": "{method} + έξοδα πληρωμής",
  "order.free": "Δωρεάν",
  "order.vat_included": "Περιλαμβάνεται ΦΠΑ {rate}: {amount}",
  "order.vat_included_plain": "Περιλαμβάνεται ΦΠΑ: {amount}",
  "order.view": "Δείτε την παραγγελία",
  "order.shipping_title": "Αποστολή",
  "order.pickup_title": "Παραλαβή",
  "order.payment_title": "Πληρωμή",
  "order.document": "Παραστατικό: {type}",
  "order.vat_number": "ΑΦΜ {vat} · ΔΟΥ {doy}",
  "doc.receipt": "Απόδειξη",
  "doc.invoice": "Τιμολόγιο",
  "state.paid": "Πληρωμένη",
  "state.pending": "Αναμένεται πληρωμή",
  "eta.days": "Παράδοση σε {n} εργάσιμες",
  "eta.day": "Παράδοση σε 1 εργάσιμη",
  "eta.supplier": "Παράδοση σε 3–5 εργάσιμες",
  "eta.pickup": "Από το κατάστημα του Πειραιά",
  "method.courier": "ACS Courier",
  "method.express": "ACS Express",
  "method.pickup": "Παραλαβή από το κατάστημα",
  "pay.card": "Κάρτα",
  "pay.iris": "IRIS",
  "pay.bank": "Τραπεζική κατάθεση",

  "confirm.topline": "Επιβεβαίωση παραγγελίας",
  "confirm.eyebrow": "Επιβεβαίωση παραγγελίας",
  "confirm.title": "Ευχαριστούμε για την παραγγελία σας",
  "confirm.lead_paid":
    "Λάβαμε την πληρωμή σας και ετοιμάζουμε την παραγγελία. Μόλις φύγει, θα σας στείλουμε νέο email με τον αριθμό αποστολής της ACS.",
  "confirm.lead_paid_pickup":
    "Λάβαμε την πληρωμή σας και ετοιμάζουμε την παραγγελία. Θα σας ενημερώσουμε μόλις είναι έτοιμη για παραλαβή από το κατάστημα.",
  "confirm.lead_pending":
    "Λάβαμε την παραγγελία σας. Θα την ετοιμάσουμε μόλις ολοκληρωθεί η πληρωμή.",
  "confirm.lead_bank":
    "Λάβαμε την παραγγελία σας. Για να την ετοιμάσουμε, κάντε την κατάθεση με τα παρακάτω στοιχεία.",
  "confirm.subject_paid": "Η παραγγελία {number} επιβεβαιώθηκε",
  "confirm.subject": "Παραγγελία {number}: ελήφθη",
  "confirm.subject_bank": "Στοιχεία κατάθεσης για την παραγγελία {number}",
  "confirm.pre_paid": "{count} είδη · {total} · πληρωμένη",
  "confirm.pre": "{count} είδη · {total}",
  "confirm.pre_bank": "Ποσό {total} · αιτιολογία {reference}",
  "supplier.title": "Παράδοση σε 3–5 εργάσιμες",
  "supplier.text":
    "Ένα από τα είδη της παραγγελίας έρχεται από τον προμηθευτή. Για να τα λάβετε όλα μαζί, η παραγγελία θα αποσταλεί ολόκληρη μόλις φτάσει, σε 3–5 εργάσιμες.",

  "bank.title": "Στοιχεία κατάθεσης",
  "bank.bank": "Τράπεζα",
  "bank.holder": "Δικαιούχος",
  "bank.iban": "IBAN",
  "bank.amount": "Ποσό",
  "bank.reference": "Αιτιολογία",
  "bank.hold_title": "Κρατάμε την παραγγελία",
  "bank.hold": "Κρατάμε την παραγγελία και το απόθεμα για {time}. Γράψτε ακριβώς την αιτιολογία, για να ταυτιστεί η κατάθεση.",
  "bank.hold_deadline":
    "Κρατάμε την παραγγελία και το απόθεμα έως {deadline}. Γράψτε ακριβώς την αιτιολογία, για να ταυτιστεί η κατάθεση.",
  "bank.card": "Πληρωμή με κάρτα",
  "bank.card_note": "Προτιμάτε κάρτα; Πληρώστε την ίδια παραγγελία τώρα, χωρίς κατάθεση.",
  "time.hours": "{n} ώρες",
  "time.working_days": "3 εργάσιμες ημέρες",

  "paid.topline": "Πληρωμή",
  "paid.eyebrow": "Πληρωμή",
  "paid.title": "Η πληρωμή σας εγκρίθηκε",
  "paid.lead":
    "Λάβαμε την πληρωμή για την παραγγελία {number}. Την ετοιμάζουμε και θα σας στείλουμε νέο email μόλις φύγει.",
  "paid.amount": "Ποσό",
  "paid.method": "Τρόπος πληρωμής",
  "paid.date": "Ημερομηνία πληρωμής",
  "paid.subject": "Η πληρωμή για την παραγγελία {number} εγκρίθηκε",
  "paid.pre": "{amount} · {method}",

  "failed.topline": "Πληρωμή",
  "failed.eyebrow": "Πληρωμή",
  "failed.title": "Η πληρωμή δεν ολοκληρώθηκε",
  "failed.lead":
    "Η συναλλαγή για την παραγγελία {number} δεν εγκρίθηκε από την τράπεζα. Δεν έγινε καμία χρέωση.",
  "failed.reason": "Αιτία",
  "failed.reason_text": "Η συναλλαγή δεν εγκρίθηκε από την τράπεζα",
  "failed.code": "Κωδικός",
  "failed.retry": "Δοκιμάστε ξανά",
  "failed.retry_note": "Ο σύνδεσμος ανοίγει ξανά την πληρωμή της ίδιας παραγγελίας.",
  "failed.bank_title": "Ή με κατάθεση σε τράπεζα",
  "failed.bank_text": "Καταθέστε {amount} με αιτιολογία {number}.",
  "failed.subject": "Η πληρωμή δεν ολοκληρώθηκε: παραγγελία {number}",
  "failed.pre": "Δεν έγινε καμία χρέωση. Δοκιμάστε ξανά ή επιλέξτε κατάθεση.",

  "shipped.topline": "Αποστολή",
  "shipped.eyebrow": "Αποστολή",
  "shipped.title": "Η παραγγελία σας είναι καθ' οδόν",
  "shipped.lead":
    "Η παραγγελία {number} παραδόθηκε στην ACS. Με τον αριθμό αποστολής βλέπετε πού βρίσκεται το δέμα.",
  "shipped.tracking": "Αριθμός αποστολής",
  "shipped.track": "Παρακολούθηση δέματος",
  "shipped.courier": "Courier",
  "shipped.eta": "Εκτιμώμενη παράδοση",
  "shipped.packages": "Δέματα",
  "shipped.weight": "Βάρος",
  "shipped.document": "Παραστατικό",
  "shipped.eta_days": "{n} εργάσιμες",
  "shipped.eta_day": "1 εργάσιμη",
  "shipped.eta_default": "1–3 εργάσιμες",
  "shipped.subject": "Η παραγγελία {number} απεστάλη",
  "shipped.pre": "ACS · {voucher}",
  "shipped.pre_eta": "ACS · {voucher} · παράδοση σε {eta}",

  "delivered.topline": "Παράδοση",
  "delivered.eyebrow": "Παράδοση",
  "delivered.title": "Η παραγγελία σας παραδόθηκε",
  "delivered.lead": "Η παραγγελία {number} παραδόθηκε. Ελέγξτε τα είδη σας όσο είναι ακόμη στη συσκευασία τους.",
  "delivered.at": "Παράδοση",
  "delivered.where": "Διεύθυνση",
  "delivered.check_title": "Κάτι δεν είναι σωστό;",
  "delivered.check":
    "Απαντήστε σε αυτό το email ή καλέστε μας. Για επιστροφές και εγγυήσεις ισχύουν όσα γράφει η σελίδα επιστροφών.",
  "delivered.returns": "Επιστροφές και εγγυήσεις",
  "delivered.subject": "Η παραγγελία {number} παραδόθηκε",
  "delivered.pre": "Ελέγξτε τα είδη σας. Πρόβλημα; Απαντήστε σε αυτό το email.",

  "status.topline": "Ενημέρωση παραγγελίας",
  "status.eyebrow": "Ενημέρωση παραγγελίας",
  "status.title": "Νέα κατάσταση παραγγελίας",
  "status.lead": "Η παραγγελία {number} είναι τώρα: {status}.",
  "status.now": "Νέα κατάσταση",
  "status.tracking": "Αριθμός αποστολής ACS",
  "status.subject": "Παραγγελία {number}: {status}",
  "status.pre": "{number} · {status}",

  "correction.topline": "Διόρθωση τιμής",
  "correction.eyebrow": "Διόρθωση τιμής",
  "correction.title": "Συγγνώμη για το λάθος",
  "correction.lead":
    "Υπολογίσαμε λάθος τα μεταφορικά της παραγγελίας {number}: {old} αντί για {new}. Το λάθος ήταν δικό μας. Δεν έγινε καμία χρέωση.",
  "correction.products": "Προϊόντα",
  "correction.shipping_old": "Μεταφορικά (πριν)",
  "correction.shipping_new": "Μεταφορικά",
  "correction.total_old": "Σύνολο (πριν)",
  "correction.total_new": "Νέο σύνολο",
  "correction.pay": "Ολοκλήρωση πληρωμής",
  "correction.pay_note": "Ο σύνδεσμος χρεώνει το σωστό ποσό, όποτε κι αν τον ανοίξετε.",
  "correction.subject": "Διόρθωση τιμής: παραγγελία {number}",
  "correction.pre": "Υπολογίσαμε λάθος τα μεταφορικά. Νέο σύνολο {total}, χωρίς καμία χρέωση ακόμη.",

  "review.topline": "Αξιολόγηση",
  "review.eyebrow": "Αξιολόγηση",
  "review.title": "Πώς σας φάνηκαν;",
  "review.lead":
    "Γράψτε δυο λόγια για όσα παραλάβατε με την παραγγελία {number}. Βοηθάτε όποιον ψάχνει το ίδιο εργαλείο να επιλέξει σωστά.",
  "review.items": "Τα προϊόντα σας ({count})",
  "review.action": "Αξιολόγηση",
  "review.cta": "Αξιολογήστε",
  "review.problem_title": "Κάτι δεν πήγε καλά;",
  "review.problem": "Μη γράψετε αξιολόγηση: απαντήστε σε αυτό το email και θα το λύσουμε.",
  "review.subject": "Πώς σας φάνηκαν; Αξιολογήστε την παραγγελία {number}",
  "review.pre": "Ένα λεπτό, και βοηθάτε άλλους να επιλέξουν σωστά.",

  "verify.topline": "Επιβεβαίωση email",
  "verify.eyebrow": "Επιβεβαίωση email",
  "verify.title": "Επιβεβαιώστε το email σας",
  "verify.lead":
    "Επιβεβαιώστε ότι αυτό το email είναι δικό σας. Μετά θα βρείτε στον λογαριασμό σας και τις παραγγελίες που κάνατε ως επισκέπτης με αυτό το email.",
  "verify.cta": "Επιβεβαίωση email",
  "verify.valid": "Ο σύνδεσμος ισχύει {hours} ώρες και χρησιμοποιείται μία φορά.",
  "verify.fallback": "Αν το κουμπί δεν ανοίγει, αντιγράψτε αυτόν τον σύνδεσμο στον browser:",
  "verify.ignore_title": "Δεν το ζητήσατε εσείς;",
  "verify.ignore":
    "Αγνοήστε αυτό το email: δεν αλλάζει τίποτα στον λογαριασμό σας και ο σύνδεσμος λήγει από μόνος του.",
  "verify.subject": "Επιβεβαίωση email",
  "verify.pre": "Επιβεβαιώστε το email σας. Ο σύνδεσμος ισχύει {hours} ώρες.",
  "claim.eyebrow": "Ο λογαριασμός σας",
  "claim.title": "Ολοκληρώστε την εγγραφή σας",
  "claim.lead":
    "Ζητήσατε πρόσβαση στον λογαριασμό σας με βάση την παραγγελία {number}. Ορίστε κωδικό και θα βρείτε εκεί όλες τις παραγγελίες που έχετε κάνει με αυτό το email.",
  "claim.cta": "Ορισμός κωδικού",
  "claim.ignore":
    "Αγνοήστε αυτό το email: δεν δημιουργήθηκε λογαριασμός και δεν άλλαξε τίποτα στις παραγγελίες σας. Ο σύνδεσμος λήγει από μόνος του.",
  "claim.subject": "Ολοκληρώστε την εγγραφή σας",
  "claim.pre": "Ορίστε κωδικό και δείτε όλες τις παραγγελίες σας. Ο σύνδεσμος ισχύει {hours} ώρες.",

  "reset.topline": "Επαναφορά κωδικού",
  "reset.eyebrow": "Επαναφορά κωδικού",
  "reset.title": "Ορίστε νέο κωδικό",
  "reset.lead": "Ζητήθηκε νέος κωδικός για τον λογαριασμό σας στο Milwaukee Heavy Duty Centre.",
  "reset.cta": "Ορισμός νέου κωδικού",
  "reset.valid": "Ο σύνδεσμος ισχύει {time} και χρησιμοποιείται μία φορά.",
  "reset.requested": "Αίτημα",
  "reset.device": "Συσκευή",
  "reset.ip": "Διεύθυνση IP",
  "reset.ignore_title": "Δεν το ζητήσατε εσείς;",
  "reset.ignore": "Αγνοήστε το μήνυμα: ο κωδικός σας δεν άλλαξε.",
  "reset.subject": "Επαναφορά κωδικού πρόσβασης",
  "reset.pre": "Ο σύνδεσμος ισχύει {time}.",

  "changed.topline": "Ασφάλεια λογαριασμού",
  "changed.eyebrow": "Ασφάλεια λογαριασμού",
  "changed.title": "Ο κωδικός σας άλλαξε",
  "changed.lead": "Ο κωδικός πρόσβασης του λογαριασμού σας άλλαξε. Αν το κάνατε εσείς, δεν χρειάζεται τίποτα άλλο.",
  "changed.when": "Ημερομηνία",
  "changed.warn_title": "Δεν το κάνατε εσείς;",
  "changed.warn": "Καλέστε μας αμέσως στο {phone} ή απαντήστε σε αυτό το email.",
  "changed.subject": "Ο κωδικός πρόσβασής σας άλλαξε",
  "changed.pre": "Αν δεν το κάνατε εσείς, επικοινωνήστε αμέσως μαζί μας.",

  "welcome.topline": "Λογαριασμός",
  "welcome.eyebrow": "Λογαριασμός",
  "welcome.title": "Ο λογαριασμός σας είναι έτοιμος",
  "welcome.lead":
    "Στον λογαριασμό σας βλέπετε τις παραγγελίες σας και πού βρίσκονται, κρατάτε διευθύνσεις και αγαπημένα, και ξαναπαραγγέλνετε με ένα κλικ.",
  "welcome.cta": "Ο λογαριασμός μου",
  "welcome.subject": "Ο λογαριασμός σας είναι έτοιμος",
  "welcome.pre": "Παραγγελίες, διευθύνσεις και αγαπημένα σε ένα σημείο.",

  "subscribe.topline": "Newsletter",
  "subscribe.eyebrow": "Newsletter",
  "subscribe.title": "Επιβεβαιώστε την εγγραφή σας",
  "subscribe.lead": "Ένα κλικ και τελειώσαμε. Χωρίς επιβεβαίωση δεν σας στέλνουμε τίποτα.",
  "subscribe.cta": "Επιβεβαίωση εγγραφής",
  "subscribe.what_title": "Τι θα λαμβάνετε",
  "subscribe.what_offers": "Προσφορές σε εργαλεία, μπαταρίες και PACKOUT, με ημερομηνία λήξης.",
  "subscribe.what_new": "Νέα προϊόντα Milwaukee μόλις φτάσουν στο κατάστημα.",
  "subscribe.what_news": "Νέα και οδηγούς για τις πλατφόρμες M12 και M18.",
  "subscribe.valid": "Ο σύνδεσμος ισχύει {hours} ώρες.",
  "subscribe.ignore": "Αν δεν ζητήσατε εγγραφή, αγνοήστε το μήνυμα: δεν θα λάβετε τίποτα.",
  "subscribe.subject": "Επιβεβαιώστε την εγγραφή σας στο newsletter",
  "subscribe.pre": "Ένα κλικ και τελειώσαμε. Χωρίς επιβεβαίωση δεν στέλνουμε τίποτα.",

  "nl.section_title": "Οι προσφορές του μήνα",
  "nl.all_offers": "Όλες οι προσφορές",
  "nl.delivery":
    "Όσα είναι σε απόθεμα τα παραλαμβάνετε την ίδια μέρα από το κατάστημα του Πειραιά ή με courier. Όσα έρχονται από τον προμηθευτή φτάνουν σε 3–5 εργάσιμες. Τα μεταφορικά είναι δωρεάν για παραγγελίες άνω των {threshold} (καθαρή αξία).",
  "nl.prices_until": "Τιμές με ΦΠΑ. Ισχύουν έως {date} ή έως εξαντλήσεως των αποθεμάτων.",
  "nl.prices": "Τιμές με ΦΠΑ, έως εξαντλήσεως των αποθεμάτων.",
  "nl.new_section": "Μόλις έφτασαν",
  "nl.all_new": "Όλα τα νέα προϊόντα",
  "nl.read_more": "Διαβάστε περισσότερα",
  "nl.topline_news": "Newsletter",
} as const;

export type StringKey = keyof typeof el;
type Dict = Record<StringKey, string>;

const en: Dict = {
  "nav.offers": "Offers",

  "footer.store": "Our store in Piraeus",
  "footer.sunday": "Closed on Sundays",
  "footer.directions": "Directions on the map",
  "footer.contact": "Contact",
  "footer.preferences": "Email preferences",
  "footer.unsubscribe": "Unsubscribe",
  "footer.operator_html":
    'Milwaukee Heavy Duty Centre Piraeus is operated by <b style="color:#ffffff;">{company}</b> · VAT no. {vat} · GEMI {gemi}.',
  "footer.trademarks":
    "Milwaukee®, M12™, M18™, MX FUEL™, PACKOUT™, ONE-KEY™ and REDLITHIUM™ are trademarks of Milwaukee Tool.",
  "footer.terms": "Terms of use",
  "footer.privacy": "Privacy",
  "footer.why_newsletter": "You are receiving this email because you subscribed to the Milwaukee Heavy Duty Centre newsletter.",
  "footer.why_order":
    "You are receiving this email because you placed an order on {site}. It is an update about your order, not advertising.",
  "footer.why_account": "You are receiving this email about your account on {site}. It is not advertising.",
  "footer.why_subscribe":
    "You are receiving this email because a subscription to the {site} newsletter was requested with this address.",

  hours: "Mon–Fri {wo}–{wc} · Sat {so}–{sc}",

  "help.call": "Call us on",
  "help.or_reply": "or reply to this email.",
  "help.order": "Questions about your order?",
  "help.account": "Need help?",

  "card.view": "View",
  "card.bare": "No battery",
  "card.new": "New",
  "avail.se_apothema": "In stock",
  "avail.teleftaio": "Last one in stock",
  "avail.diathesimo_3_5": "Available · 3–5 working days",
  "avail.paradosi_1_3": "Delivery in 1–3 working days",

  "line.code": "Code",
  "line.qty": "Qty",

  "order.number": "Order number",
  "order.date": "Date",
  "order.status": "Status",
  "order.items": "Your items ({count})",
  "order.prices_gross": "Prices incl. VAT",
  "order.total": "Total",
  "order.subtotal": "Subtotal",
  "order.discount": "Discount",
  "order.shipping": "Shipping · {method}",
  "order.payment_fee": "{method} + payment fee",
  "order.free": "Free",
  "order.vat_included": "Includes VAT {rate}: {amount}",
  "order.vat_included_plain": "Includes VAT: {amount}",
  "order.view": "View your order",
  "order.shipping_title": "Shipping",
  "order.pickup_title": "Collection",
  "order.payment_title": "Payment",
  "order.document": "Document: {type}",
  "order.vat_number": "VAT no. {vat} · Tax office {doy}",
  "doc.receipt": "Receipt",
  "doc.invoice": "Invoice",
  "state.paid": "Paid",
  "state.pending": "Awaiting payment",
  "eta.days": "Delivery in {n} working days",
  "eta.day": "Delivery in 1 working day",
  "eta.supplier": "Delivery in 3–5 working days",
  "eta.pickup": "From our Piraeus store",
  "method.courier": "ACS Courier",
  "method.express": "ACS Express",
  "method.pickup": "Collection from the store",
  "pay.card": "Card",
  "pay.iris": "IRIS",
  "pay.bank": "Bank transfer",

  "confirm.topline": "Order confirmation",
  "confirm.eyebrow": "Order confirmation",
  "confirm.title": "Thank you for your order",
  "confirm.lead_paid":
    "We have received your payment and are preparing your order. As soon as it leaves, we will email you the ACS tracking number.",
  "confirm.lead_paid_pickup":
    "We have received your payment and are preparing your order. We will let you know as soon as it is ready for collection at the store.",
  "confirm.lead_pending": "We have received your order. We will prepare it as soon as the payment is completed.",
  "confirm.lead_bank": "We have received your order. To prepare it, please make the bank transfer with the details below.",
  "confirm.subject_paid": "Order {number} confirmed",
  "confirm.subject": "Order {number} received",
  "confirm.subject_bank": "Bank transfer details for order {number}",
  "confirm.pre_paid": "{count} items · {total} · paid",
  "confirm.pre": "{count} items · {total}",
  "confirm.pre_bank": "Amount {total} · reference {reference}",
  "supplier.title": "Delivery in 3–5 working days",
  "supplier.text":
    "One of the items in your order comes from our supplier. So that you receive everything together, the whole order will ship as soon as it arrives, in 3–5 working days.",

  "bank.title": "Bank transfer details",
  "bank.bank": "Bank",
  "bank.holder": "Account holder",
  "bank.iban": "IBAN",
  "bank.amount": "Amount",
  "bank.reference": "Reference",
  "bank.hold_title": "We are holding your order",
  "bank.hold": "We hold the order and the stock for {time}. Please write the reference exactly, so the transfer can be matched.",
  "bank.hold_deadline":
    "We hold the order and the stock until {deadline}. Please write the reference exactly, so the transfer can be matched.",
  "bank.card": "Pay by card",
  "bank.card_note": "Prefer a card? Pay for the same order now, without a transfer.",
  "time.hours": "{n} hours",
  "time.working_days": "3 working days",

  "paid.topline": "Payment",
  "paid.eyebrow": "Payment",
  "paid.title": "Your payment was approved",
  "paid.lead": "We have received the payment for order {number}. We are preparing it and will email you again as soon as it leaves.",
  "paid.amount": "Amount",
  "paid.method": "Payment method",
  "paid.date": "Payment date",
  "paid.subject": "Payment for order {number} approved",
  "paid.pre": "{amount} · {method}",

  "failed.topline": "Payment",
  "failed.eyebrow": "Payment",
  "failed.title": "Your payment did not go through",
  "failed.lead": "The bank did not approve the transaction for order {number}. You have not been charged.",
  "failed.reason": "Reason",
  "failed.reason_text": "The bank did not approve the transaction",
  "failed.code": "Code",
  "failed.retry": "Try again",
  "failed.retry_note": "The link reopens the payment for the same order.",
  "failed.bank_title": "Or pay by bank transfer",
  "failed.bank_text": "Transfer {amount} with the reference {number}.",
  "failed.subject": "Payment not completed: order {number}",
  "failed.pre": "You have not been charged. Try again or choose a bank transfer.",

  "shipped.topline": "Shipping",
  "shipped.eyebrow": "Shipping",
  "shipped.title": "Your order is on its way",
  "shipped.lead": "Order {number} has been handed to ACS. The tracking number shows where your parcel is.",
  "shipped.tracking": "Tracking number",
  "shipped.track": "Track your parcel",
  "shipped.courier": "Courier",
  "shipped.eta": "Estimated delivery",
  "shipped.packages": "Parcels",
  "shipped.weight": "Weight",
  "shipped.document": "Document",
  "shipped.eta_days": "{n} working days",
  "shipped.eta_day": "1 working day",
  "shipped.eta_default": "1–3 working days",
  "shipped.subject": "Order {number} has shipped",
  "shipped.pre": "ACS · {voucher}",
  "shipped.pre_eta": "ACS · {voucher} · delivery in {eta}",

  "delivered.topline": "Delivery",
  "delivered.eyebrow": "Delivery",
  "delivered.title": "Your order has been delivered",
  "delivered.lead": "Order {number} has been delivered. Please check your items while they are still in their packaging.",
  "delivered.at": "Delivered",
  "delivered.where": "Address",
  "delivered.check_title": "Something not right?",
  "delivered.check": "Reply to this email or call us. Returns and warranties follow the terms on our returns page.",
  "delivered.returns": "Returns and warranties",
  "delivered.subject": "Order {number} delivered",
  "delivered.pre": "Check your items. A problem? Reply to this email.",

  "status.topline": "Order update",
  "status.eyebrow": "Order update",
  "status.title": "Your order status changed",
  "status.lead": "Order {number} is now: {status}.",
  "status.now": "New status",
  "status.tracking": "ACS tracking number",
  "status.subject": "Order {number}: {status}",
  "status.pre": "{number} · {status}",

  "correction.topline": "Price correction",
  "correction.eyebrow": "Price correction",
  "correction.title": "Sorry for our mistake",
  "correction.lead":
    "We calculated the shipping of order {number} wrongly: {old} instead of {new}. The mistake was ours. You have not been charged.",
  "correction.products": "Products",
  "correction.shipping_old": "Shipping (before)",
  "correction.shipping_new": "Shipping",
  "correction.total_old": "Total (before)",
  "correction.total_new": "New total",
  "correction.pay": "Complete payment",
  "correction.pay_note": "The link charges the correct amount, whenever you open it.",
  "correction.subject": "Price correction: order {number}",
  "correction.pre": "We miscalculated the shipping. New total {total}, nothing charged yet.",

  "review.topline": "Review",
  "review.eyebrow": "Review",
  "review.title": "How did they work for you?",
  "review.lead":
    "Write a few words about what you received with order {number}. You help anyone looking for the same tool to choose well.",
  "review.items": "Your products ({count})",
  "review.action": "Review",
  "review.cta": "Write a review",
  "review.problem_title": "Something went wrong?",
  "review.problem": "Don't write a review: reply to this email and we will sort it out.",
  "review.subject": "How did they work? Review order {number}",
  "review.pre": "One minute, and you help others choose well.",

  "verify.topline": "Email confirmation",
  "verify.eyebrow": "Email confirmation",
  "verify.title": "Confirm your email",
  "verify.lead":
    "Confirm that this email address is yours. Your account will then also show the orders you placed as a guest with this email.",
  "verify.cta": "Confirm email",
  "verify.valid": "The link is valid for {hours} hours and works once.",
  "verify.fallback": "If the button does not open, copy this link into your browser:",
  "verify.ignore_title": "Didn't ask for this?",
  "verify.ignore": "Ignore this email: nothing changes in your account and the link expires on its own.",
  "verify.subject": "Confirm your email",
  "verify.pre": "Confirm your email. The link is valid for {hours} hours.",
  "claim.eyebrow": "Your account",
  "claim.title": "Complete your registration",
  "claim.lead":
    "You asked for access to your account based on order {number}. Choose a password and you will find there every order you have placed with this email.",
  "claim.cta": "Set a password",
  "claim.ignore":
    "Ignore this email: no account was created and nothing changed in your orders. The link expires on its own.",
  "claim.subject": "Complete your registration",
  "claim.pre": "Set a password and see all your orders. The link is valid for {hours} hours.",

  "reset.topline": "Password reset",
  "reset.eyebrow": "Password reset",
  "reset.title": "Set a new password",
  "reset.lead": "A new password was requested for your Milwaukee Heavy Duty Centre account.",
  "reset.cta": "Set a new password",
  "reset.valid": "The link is valid for {time} and works once.",
  "reset.requested": "Requested",
  "reset.device": "Device",
  "reset.ip": "IP address",
  "reset.ignore_title": "Didn't ask for this?",
  "reset.ignore": "Ignore this message: your password has not changed.",
  "reset.subject": "Reset your password",
  "reset.pre": "The link is valid for {time}.",

  "changed.topline": "Account security",
  "changed.eyebrow": "Account security",
  "changed.title": "Your password was changed",
  "changed.lead": "The password of your account was changed. If it was you, there is nothing else to do.",
  "changed.when": "Date",
  "changed.warn_title": "Wasn't you?",
  "changed.warn": "Call us immediately on {phone} or reply to this email.",
  "changed.subject": "Your password was changed",
  "changed.pre": "If it wasn't you, contact us immediately.",

  "welcome.topline": "Account",
  "welcome.eyebrow": "Account",
  "welcome.title": "Your account is ready",
  "welcome.lead":
    "In your account you see your orders and where they are, keep addresses and favourites, and reorder with one click.",
  "welcome.cta": "My account",
  "welcome.subject": "Your account is ready",
  "welcome.pre": "Orders, addresses and favourites in one place.",

  "subscribe.topline": "Newsletter",
  "subscribe.eyebrow": "Newsletter",
  "subscribe.title": "Confirm your subscription",
  "subscribe.lead": "One click and you are done. Without confirmation we send you nothing.",
  "subscribe.cta": "Confirm subscription",
  "subscribe.what_title": "What you will receive",
  "subscribe.what_offers": "Offers on tools, batteries and PACKOUT, each with an end date.",
  "subscribe.what_new": "New Milwaukee products as soon as they reach the store.",
  "subscribe.what_news": "News and guides about the M12 and M18 platforms.",
  "subscribe.valid": "The link is valid for {hours} hours.",
  "subscribe.ignore": "If you did not ask to subscribe, ignore this message: you will receive nothing.",
  "subscribe.subject": "Confirm your newsletter subscription",
  "subscribe.pre": "One click and you are done. Without confirmation we send nothing.",

  "nl.section_title": "This month's offers",
  "nl.all_offers": "All offers",
  "nl.delivery":
    "Items in stock can be collected the same day from our Piraeus store or sent by courier. Items from our supplier arrive in 3–5 working days. Shipping is free on orders over {threshold} (excl. VAT).",
  "nl.prices_until": "Prices incl. VAT. Valid until {date} or while stocks last.",
  "nl.prices": "Prices incl. VAT, while stocks last.",
  "nl.new_section": "Just arrived",
  "nl.all_new": "All new products",
  "nl.read_more": "Read more",
  "nl.topline_news": "Newsletter",
};

const it: Dict = {
  "nav.offers": "Offerte",

  "footer.store": "Il negozio al Pireo",
  "footer.sunday": "Domenica chiuso",
  "footer.directions": "Indicazioni sulla mappa",
  "footer.contact": "Contatti",
  "footer.preferences": "Preferenze email",
  "footer.unsubscribe": "Annulla l'iscrizione",
  "footer.operator_html":
    'Il Milwaukee Heavy Duty Centre del Pireo è gestito da <b style="color:#ffffff;">{company}</b> · P. IVA {vat} · GEMI {gemi}.',
  "footer.trademarks":
    "Milwaukee®, M12™, M18™, MX FUEL™, PACKOUT™, ONE-KEY™ e REDLITHIUM™ sono marchi di Milwaukee Tool.",
  "footer.terms": "Condizioni d'uso",
  "footer.privacy": "Privacy",
  "footer.why_newsletter": "Ricevete questa email perché vi siete iscritti alla newsletter del Milwaukee Heavy Duty Centre.",
  "footer.why_order":
    "Ricevete questa email perché avete effettuato un ordine su {site}. È un aggiornamento sul vostro ordine, non pubblicità.",
  "footer.why_account": "Ricevete questa email per il vostro account su {site}. Non è pubblicità.",
  "footer.why_subscribe":
    "Ricevete questa email perché con questo indirizzo è stata richiesta l'iscrizione alla newsletter di {site}.",

  hours: "Lun–Ven {wo}–{wc} · Sab {so}–{sc}",

  "help.call": "Chiamateci al",
  "help.or_reply": "oppure rispondete a questa email.",
  "help.order": "Domande sull'ordine?",
  "help.account": "Serve aiuto?",

  "card.view": "Scopri",
  "card.bare": "Senza batteria",
  "card.new": "Novità",
  "avail.se_apothema": "Disponibile",
  "avail.teleftaio": "Ultimo pezzo",
  "avail.diathesimo_3_5": "Disponibile · 3–5 giorni lavorativi",
  "avail.paradosi_1_3": "Consegna in 1–3 giorni lavorativi",

  "line.code": "Cod.",
  "line.qty": "Qtà",

  "order.number": "Numero d'ordine",
  "order.date": "Data",
  "order.status": "Stato",
  "order.items": "I vostri articoli ({count})",
  "order.prices_gross": "Prezzi IVA inclusa",
  "order.total": "Totale",
  "order.subtotal": "Subtotale",
  "order.discount": "Sconto",
  "order.shipping": "Spedizione · {method}",
  "order.payment_fee": "{method} + commissione di pagamento",
  "order.free": "Gratuita",
  "order.vat_included": "IVA {rate} inclusa: {amount}",
  "order.vat_included_plain": "IVA inclusa: {amount}",
  "order.view": "Vedi l'ordine",
  "order.shipping_title": "Spedizione",
  "order.pickup_title": "Ritiro",
  "order.payment_title": "Pagamento",
  "order.document": "Documento: {type}",
  "order.vat_number": "P. IVA {vat} · Ufficio imposte {doy}",
  "doc.receipt": "Scontrino",
  "doc.invoice": "Fattura",
  "state.paid": "Pagato",
  "state.pending": "In attesa di pagamento",
  "eta.days": "Consegna in {n} giorni lavorativi",
  "eta.day": "Consegna in 1 giorno lavorativo",
  "eta.supplier": "Consegna in 3–5 giorni lavorativi",
  "eta.pickup": "Dal nostro negozio al Pireo",
  "method.courier": "ACS Courier",
  "method.express": "ACS Express",
  "method.pickup": "Ritiro in negozio",
  "pay.card": "Carta",
  "pay.iris": "IRIS",
  "pay.bank": "Bonifico bancario",

  "confirm.topline": "Conferma d'ordine",
  "confirm.eyebrow": "Conferma d'ordine",
  "confirm.title": "Grazie per il vostro ordine",
  "confirm.lead_paid":
    "Abbiamo ricevuto il pagamento e stiamo preparando l'ordine. Appena partito, vi invieremo una nuova email con il numero di spedizione ACS.",
  "confirm.lead_paid_pickup":
    "Abbiamo ricevuto il pagamento e stiamo preparando l'ordine. Vi avviseremo appena sarà pronto per il ritiro in negozio.",
  "confirm.lead_pending": "Abbiamo ricevuto il vostro ordine. Lo prepareremo appena il pagamento sarà completato.",
  "confirm.lead_bank": "Abbiamo ricevuto il vostro ordine. Per prepararlo, effettuate il bonifico con i dati qui sotto.",
  "confirm.subject_paid": "Ordine {number} confermato",
  "confirm.subject": "Ordine {number} ricevuto",
  "confirm.subject_bank": "Dati per il bonifico dell'ordine {number}",
  "confirm.pre_paid": "{count} articoli · {total} · pagato",
  "confirm.pre": "{count} articoli · {total}",
  "confirm.pre_bank": "Importo {total} · causale {reference}",
  "supplier.title": "Consegna in 3–5 giorni lavorativi",
  "supplier.text":
    "Uno degli articoli dell'ordine arriva dal nostro fornitore. Per ricevere tutto insieme, l'ordine partirà completo appena arriva, in 3–5 giorni lavorativi.",

  "bank.title": "Dati per il bonifico",
  "bank.bank": "Banca",
  "bank.holder": "Intestatario",
  "bank.iban": "IBAN",
  "bank.amount": "Importo",
  "bank.reference": "Causale",
  "bank.hold_title": "Teniamo il vostro ordine",
  "bank.hold": "Teniamo l'ordine e la merce per {time}. Scrivete la causale esattamente, così il bonifico viene abbinato.",
  "bank.hold_deadline":
    "Teniamo l'ordine e la merce fino al {deadline}. Scrivete la causale esattamente, così il bonifico viene abbinato.",
  "bank.card": "Paga con carta",
  "bank.card_note": "Preferite la carta? Pagate lo stesso ordine adesso, senza bonifico.",
  "time.hours": "{n} ore",
  "time.working_days": "3 giorni lavorativi",

  "paid.topline": "Pagamento",
  "paid.eyebrow": "Pagamento",
  "paid.title": "Il pagamento è stato approvato",
  "paid.lead":
    "Abbiamo ricevuto il pagamento dell'ordine {number}. Lo stiamo preparando e vi scriveremo di nuovo appena partito.",
  "paid.amount": "Importo",
  "paid.method": "Metodo di pagamento",
  "paid.date": "Data del pagamento",
  "paid.subject": "Pagamento dell'ordine {number} approvato",
  "paid.pre": "{amount} · {method}",

  "failed.topline": "Pagamento",
  "failed.eyebrow": "Pagamento",
  "failed.title": "Il pagamento non è andato a buon fine",
  "failed.lead": "La banca non ha approvato la transazione per l'ordine {number}. Non è stato addebitato nulla.",
  "failed.reason": "Motivo",
  "failed.reason_text": "La banca non ha approvato la transazione",
  "failed.code": "Codice",
  "failed.retry": "Riprova",
  "failed.retry_note": "Il link riapre il pagamento dello stesso ordine.",
  "failed.bank_title": "Oppure con bonifico bancario",
  "failed.bank_text": "Versate {amount} con causale {number}.",
  "failed.subject": "Pagamento non completato: ordine {number}",
  "failed.pre": "Non è stato addebitato nulla. Riprovate o scegliete il bonifico.",

  "shipped.topline": "Spedizione",
  "shipped.eyebrow": "Spedizione",
  "shipped.title": "Il vostro ordine è in viaggio",
  "shipped.lead": "L'ordine {number} è stato affidato ad ACS. Con il numero di spedizione vedete dove si trova il pacco.",
  "shipped.tracking": "Numero di spedizione",
  "shipped.track": "Traccia il pacco",
  "shipped.courier": "Corriere",
  "shipped.eta": "Consegna prevista",
  "shipped.packages": "Colli",
  "shipped.weight": "Peso",
  "shipped.document": "Documento",
  "shipped.eta_days": "{n} giorni lavorativi",
  "shipped.eta_day": "1 giorno lavorativo",
  "shipped.eta_default": "1–3 giorni lavorativi",
  "shipped.subject": "L'ordine {number} è stato spedito",
  "shipped.pre": "ACS · {voucher}",
  "shipped.pre_eta": "ACS · {voucher} · consegna in {eta}",

  "delivered.topline": "Consegna",
  "delivered.eyebrow": "Consegna",
  "delivered.title": "Il vostro ordine è stato consegnato",
  "delivered.lead": "L'ordine {number} è stato consegnato. Controllate gli articoli finché sono ancora nella confezione.",
  "delivered.at": "Consegnato",
  "delivered.where": "Indirizzo",
  "delivered.check_title": "Qualcosa non va?",
  "delivered.check": "Rispondete a questa email o chiamateci. Resi e garanzie seguono le condizioni della pagina dei resi.",
  "delivered.returns": "Resi e garanzie",
  "delivered.subject": "Ordine {number} consegnato",
  "delivered.pre": "Controllate gli articoli. Un problema? Rispondete a questa email.",

  "status.topline": "Aggiornamento ordine",
  "status.eyebrow": "Aggiornamento ordine",
  "status.title": "Nuovo stato dell'ordine",
  "status.lead": "L'ordine {number} è ora: {status}.",
  "status.now": "Nuovo stato",
  "status.tracking": "Numero di spedizione ACS",
  "status.subject": "Ordine {number}: {status}",
  "status.pre": "{number} · {status}",

  "correction.topline": "Correzione del prezzo",
  "correction.eyebrow": "Correzione del prezzo",
  "correction.title": "Ci scusiamo per l'errore",
  "correction.lead":
    "Abbiamo calcolato male la spedizione dell'ordine {number}: {old} invece di {new}. L'errore è stato nostro. Non è stato addebitato nulla.",
  "correction.products": "Prodotti",
  "correction.shipping_old": "Spedizione (prima)",
  "correction.shipping_new": "Spedizione",
  "correction.total_old": "Totale (prima)",
  "correction.total_new": "Nuovo totale",
  "correction.pay": "Completa il pagamento",
  "correction.pay_note": "Il link addebita l'importo corretto, in qualunque momento lo apriate.",
  "correction.subject": "Correzione del prezzo: ordine {number}",
  "correction.pre": "Abbiamo sbagliato la spedizione. Nuovo totale {total}, nessun addebito finora.",

  "review.topline": "Recensione",
  "review.eyebrow": "Recensione",
  "review.title": "Come vi sono sembrati?",
  "review.lead":
    "Scrivete due parole su quanto avete ricevuto con l'ordine {number}. Aiutate chi cerca lo stesso utensile a scegliere bene.",
  "review.items": "I vostri prodotti ({count})",
  "review.action": "Recensisci",
  "review.cta": "Scrivi una recensione",
  "review.problem_title": "Qualcosa è andato storto?",
  "review.problem": "Non scrivete una recensione: rispondete a questa email e lo risolveremo.",
  "review.subject": "Come vi sono sembrati? Recensite l'ordine {number}",
  "review.pre": "Un minuto, e aiutate altri a scegliere bene.",

  "verify.topline": "Conferma email",
  "verify.eyebrow": "Conferma email",
  "verify.title": "Confermate la vostra email",
  "verify.lead":
    "Confermate che questo indirizzo email è vostro. Nel vostro account troverete anche gli ordini fatti come ospite con questa email.",
  "verify.cta": "Conferma email",
  "verify.valid": "Il link è valido {hours} ore e si usa una sola volta.",
  "verify.fallback": "Se il pulsante non si apre, copiate questo link nel browser:",
  "verify.ignore_title": "Non l'avete richiesto?",
  "verify.ignore": "Ignorate questa email: nel vostro account non cambia nulla e il link scade da solo.",
  "verify.subject": "Confermate la vostra email",
  "verify.pre": "Confermate la vostra email. Il link è valido {hours} ore.",
  "claim.eyebrow": "Il vostro account",
  "claim.title": "Completate la registrazione",
  "claim.lead":
    "Avete chiesto l'accesso al vostro account in base all'ordine {number}. Scegliete una password e troverete lì tutti gli ordini fatti con questa email.",
  "claim.cta": "Imposta la password",
  "claim.ignore":
    "Ignorate questa email: non è stato creato alcun account e nei vostri ordini non è cambiato nulla. Il link scade da solo.",
  "claim.subject": "Completate la registrazione",
  "claim.pre": "Impostate una password e vedete tutti i vostri ordini. Il link è valido {hours} ore.",

  "reset.topline": "Reimpostazione password",
  "reset.eyebrow": "Reimpostazione password",
  "reset.title": "Impostate una nuova password",
  "reset.lead": "È stata richiesta una nuova password per il vostro account Milwaukee Heavy Duty Centre.",
  "reset.cta": "Imposta nuova password",
  "reset.valid": "Il link è valido {time} e si usa una sola volta.",
  "reset.requested": "Richiesta",
  "reset.device": "Dispositivo",
  "reset.ip": "Indirizzo IP",
  "reset.ignore_title": "Non l'avete richiesto?",
  "reset.ignore": "Ignorate il messaggio: la vostra password non è cambiata.",
  "reset.subject": "Reimpostazione della password",
  "reset.pre": "Il link è valido {time}.",

  "changed.topline": "Sicurezza dell'account",
  "changed.eyebrow": "Sicurezza dell'account",
  "changed.title": "La vostra password è cambiata",
  "changed.lead": "La password del vostro account è stata cambiata. Se siete stati voi, non serve altro.",
  "changed.when": "Data",
  "changed.warn_title": "Non siete stati voi?",
  "changed.warn": "Chiamateci subito al {phone} oppure rispondete a questa email.",
  "changed.subject": "La vostra password è cambiata",
  "changed.pre": "Se non siete stati voi, contattateci subito.",

  "welcome.topline": "Account",
  "welcome.eyebrow": "Account",
  "welcome.title": "Il vostro account è pronto",
  "welcome.lead":
    "Nel vostro account vedete gli ordini e dove si trovano, salvate indirizzi e preferiti e riordinate con un clic.",
  "welcome.cta": "Il mio account",
  "welcome.subject": "Il vostro account è pronto",
  "welcome.pre": "Ordini, indirizzi e preferiti in un unico posto.",

  "subscribe.topline": "Newsletter",
  "subscribe.eyebrow": "Newsletter",
  "subscribe.title": "Confermate l'iscrizione",
  "subscribe.lead": "Un clic e abbiamo finito. Senza conferma non vi inviamo nulla.",
  "subscribe.cta": "Conferma l'iscrizione",
  "subscribe.what_title": "Cosa riceverete",
  "subscribe.what_offers": "Offerte su utensili, batterie e PACKOUT, ciascuna con una data di scadenza.",
  "subscribe.what_new": "Le novità Milwaukee appena arrivano in negozio.",
  "subscribe.what_news": "Notizie e guide sulle piattaforme M12 e M18.",
  "subscribe.valid": "Il link è valido {hours} ore.",
  "subscribe.ignore": "Se non avete chiesto l'iscrizione, ignorate il messaggio: non riceverete nulla.",
  "subscribe.subject": "Confermate l'iscrizione alla newsletter",
  "subscribe.pre": "Un clic e abbiamo finito. Senza conferma non inviamo nulla.",

  "nl.section_title": "Le offerte del mese",
  "nl.all_offers": "Tutte le offerte",
  "nl.delivery":
    "Gli articoli disponibili si ritirano in giornata nel nostro negozio del Pireo o arrivano con corriere. Quelli dal fornitore arrivano in 3–5 giorni lavorativi. La spedizione è gratuita per ordini oltre {threshold} (IVA esclusa).",
  "nl.prices_until": "Prezzi IVA inclusa. Validi fino al {date} o fino a esaurimento scorte.",
  "nl.prices": "Prezzi IVA inclusa, fino a esaurimento scorte.",
  "nl.new_section": "Appena arrivati",
  "nl.all_new": "Tutti i nuovi prodotti",
  "nl.read_more": "Leggi di più",
  "nl.topline_news": "Newsletter",
};

/**
 * The shop's own emails (new order, status change) and the admin password
 * reset: Greek only, never shown to a customer.
 */
const INTERNAL = {
  "internal.why": "Εσωτερική ειδοποίηση του Milwaukee Heavy Duty Centre. Δεν στάλθηκε σε πελάτη.",
  "internal.new_eyebrow": "Νέα παραγγελία",
  "internal.paid": "Πληρωμένη",
  "internal.unpaid": "Εκκρεμεί πληρωμή",
  "internal.customer": "Πελάτης",
  "internal.email": "Email",
  "internal.phone": "Τηλέφωνο",
  "internal.address": "Διεύθυνση",
  "internal.payment": "Πληρωμή",
  "internal.shipping": "Αποστολή",
  "internal.document": "Παραστατικό",
  "internal.company": "Επωνυμία",
  "internal.vat": "ΑΦΜ · ΔΟΥ",
  "internal.supplier": "Από προμηθευτή",
  "internal.supplier_text": "Περιέχει είδος από τον προμηθευτή: η παραγγελία φεύγει ολόκληρη σε 3–5 εργάσιμες.",
  "internal.notes": "Σημειώσεις πελάτη",
  "internal.items": "Είδη ({count})",
  "internal.total": "Σύνολο",
  "internal.admin": "Άνοιγμα στη διαχείριση",
  "internal.new_subject": "Νέα παραγγελία {number}: {total}",
  "internal.new_subject_unpaid": "Νέα παραγγελία {number}: {total} (ΕΚΚΡΕΜΕΙ ΠΛΗΡΩΜΗ)",
  "internal.status_eyebrow": "Αλλαγή κατάστασης",
  "internal.status_title": "Η παραγγελία {number} άλλαξε κατάσταση",
  "internal.status_now": "Νέα κατάσταση",
  "internal.status_lead": "Ο πελάτης ενημερώθηκε με email στα {language}.",
  "internal.status_subject": "Παραγγελία {number}: {status}",
  "internal.topline": "Εσωτερικό",
  "lang.el": "ελληνικά",
  "lang.en": "αγγλικά",
  "lang.it": "ιταλικά",

  "admin.why": "Email ασφαλείας της διαχείρισης του Milwaukee Heavy Duty Centre.",
  "admin.eyebrow": "Διαχείριση",
  "admin.title": "Επαναφορά κωδικού διαχείρισης",
  "admin.lead": "Ζητήθηκε νέος κωδικός για τον λογαριασμό διαχείρισης {email}.",
  "admin.subject": "Επαναφορά κωδικού διαχείρισης: Milwaukee Heavy Duty Centre",
  "admin.pre": "Ο σύνδεσμος ισχύει για {minutes} λεπτά.",
  "admin.valid": "Ο σύνδεσμος ισχύει {minutes} λεπτά και χρησιμοποιείται μία φορά.",
} as const;

export type InternalKey = keyof typeof INTERNAL;
export type AnyKey = StringKey | InternalKey;

const TABLE: Record<Locale, Dict> = { el, en, it };

/** The raw string, or throws — a missing word is a bug, not an empty space. */
export function rawString(locale: Locale, key: string): string {
  const value =
    (TABLE[locale] as Record<string, string>)[key] ?? (INTERNAL as Record<string, string>)[key];
  if (value === undefined) throw new Error(`[mail] missing string «${key}» (${locale})`);
  return value;
}

/** Fill `{name}` placeholders; a missing value throws. `escape` runs on each value. */
export function fill(
  template: string,
  params: Record<string, unknown>,
  escape: (s: string) => string = (s) => s,
): string {
  return template.replace(/\{(\w+)\}/g, (_, name: string) => {
    const value = params[name];
    if (value === undefined || value === null || value === "") {
      throw new Error(`[mail] empty value for {${name}} in «${template.slice(0, 40)}…»`);
    }
    return escape(String(value));
  });
}

/** A string in plain text, placeholders filled. For subjects, preheaders and data. */
export function t(locale: Locale, key: AnyKey, params: Record<string, unknown> = {}): string {
  return fill(rawString(locale, key), params);
}

/** For the test: every customer language carries every key. */
export const STRING_TABLES = TABLE;
