#!/usr/bin/env node
/**
 * Prints the fluid type tokens (`--fs-*`) for every px font size used in the
 * HDC mockups and the HDC stylesheets.
 *
 *   node scripts/fluid-type.mjs           print the :root block
 *   node scripts/fluid-type.mjs --write   also replace the block in
 *                                         src/styles/hdc/tokens.css
 *
 * Rerun it whenever a new size appears. The maths lives in fluid-type-core.mjs.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { extractFontSizes, rootBlock } from "./fluid-type-core.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const mockups = path.join(root, "docs/design/mockups");
const hdcStyles = path.join(root, "src/styles/hdc");
const tokensFile = path.join(hdcStyles, "tokens.css");

const START = "/* fluid-type:start (generated by scripts/fluid-type.mjs, do not edit by hand) */";
const END = "/* fluid-type:end */";

const listFiles = (dir, ext) =>
  readdirSync(dir)
    .filter((f) => f.endsWith(ext))
    .map((f) => path.join(dir, f));

const sizes = new Set();

for (const file of listFiles(mockups, ".html")) {
  const html = readFileSync(file, "utf8");
  // <style> blocks, plus inline style="…" attributes (the mockups set a few
  // one-off sizes inline).
  for (const m of html.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/g)) {
    extractFontSizes(m[1]).forEach((s) => sizes.add(s));
  }
  for (const m of html.matchAll(/style="([^"]*)"/g)) {
    extractFontSizes(m[1]).forEach((s) => sizes.add(s));
  }
}

for (const file of listFiles(hdcStyles, ".css")) {
  let css = readFileSync(file, "utf8");
  // Never read the generated block back in as input.
  const a = css.indexOf(START);
  const b = css.indexOf(END);
  if (a !== -1 && b !== -1) css = css.slice(0, a) + css.slice(b + END.length);
  extractFontSizes(css).forEach((s) => sizes.add(s));
}

const block = rootBlock([...sizes]);
process.stdout.write(block + "\n");

if (process.argv.includes("--write")) {
  const css = readFileSync(tokensFile, "utf8");
  const a = css.indexOf(START);
  const b = css.indexOf(END);
  if (a === -1 || b === -1) {
    console.error(`markers not found in ${path.relative(root, tokensFile)}`);
    process.exit(1);
  }
  const next = css.slice(0, a) + `${START}\n${block}\n` + css.slice(b);
  writeFileSync(tokensFile, next);
  console.error(`wrote ${sizes.size} tokens to ${path.relative(root, tokensFile)}`);
}
